# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'week6-class-lab-instagram-feed' do

pod 'AFNetworking', '2.2.1'

end

target 'week6-class-lab-instagram-feedTests' do

end

